Repository chaostreff-flensburg/hackWiki, pull requests merged in 2018-08, with the labels that each got.

#16 Feature/slate
  .babelrc
  .browserslistrc
  .eslintrc.js
  .gitignore
  assets/styles/main.jsx
  assets/styles/main.scss
  assets/styles/reset.jsx
  assets/styles/reset.scss
  assets/styles/typography.jsx
  assets/styles/typography.scss
  backpack.config.js
  components/editor/MarkHotkey.js
  components/editor/MarkdownShortcuts.js
  components/editor/RenderMark.js
  components/editor/RenderNode.js
  components/editor/editor.jsx
  components/editor/editor.vue
  components/editor/templates/EmptyDocument.js
  components/utils/ssr-loader.vue
  layouts/default.vue
  layouts/error.vue
  lib/axios.js
  next.config.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/_document.jsx
  pages/index.jsx
  pages/index.vue
  readme.md
  server/index.js
  store/index.js
Labels: editor, enhancement, frontend, server

#17 Update readme.md
  readme.md
Labels: bug

#19 Add Dockerfile and update readme.md
  .dockerignore
  .drone.yml
  Dockerfile
  readme.md
Labels: deployment, enhancement

#20 Feature/slugs
  components/editor/editor.jsx
  pages/index.jsx
  server/index.js
Labels: enhancement, frontend
